apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-flask-min
  labels:
    app: eval-flask-min
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-flask-min
  template:
    metadata:
      labels:
        app: eval-flask-min
    spec:
      containers:
      - name: eval-flask-min
        image: eval-flask-min:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
